
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.Visibility;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saadettin
 */
public class JChildPanel extends javax.swing.JFrame {

    
    Child child;
    FileTransaction file;
    DefaultTableModel exerciseModel; 
    DefaultTableModel scoresModel;
    
    public JChildPanel() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            file = new FileTransaction();                       //Dosya islemlerini yapacak nesne ürettik.
            this.child = (Child)file.dosyaInsideOku();          //inside.bin uzantili dosyayi okumak gerek ben hangi cocugun bilgilerini yansitmam gerektigini bilmem gerek.
            exerciseModel = (DefaultTableModel)exerciseTable.getModel();    //exercise nesnelerini goruntulemede kullanmak icin lazim.
            scoresModel = (DefaultTableModel)scoresTable.getModel();        //exercise nesnelerinin skorlarini goruntulemek icin lazim.
            childPanelName.setText(child.getName());
            exerciseGoruntule();
            uyari.setText("");
            exerciseIDtext.setText("");
            exerciseNameText.setText("");
        } catch (IOException ex) {
            Logger.getLogger(JChildPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        addWindowListener(new WindowAdapter() {             //Kullanici carpi isaretine bastıkran sonra programdan cikmadan once son yapmam gerekenleri yapiyorum.
            @Override
            public void windowClosing(WindowEvent e) {
                file.dosyaSil("inside.bin");            //inside.bin dosyasi ile isim kalmadi artik. Onu sileyim.
            }
        });
        
    }
    
    public void exerciseGoruntule(){                //child nesnesinin exercises ArrayListinin icindeki bilgileri goruntulemek icin bu metodu kullaniyoruz.
        int childID = child.getID();                //child nesnesinin ID bilgisini alarak ona ait exercise bilgilerini goruntuleyecem
        exerciseModel.setRowCount(0);
        for(Exercise ex : child.getExercises()){
            String aralik1 = "a:" + ex.getA1() + ".."+ ex.getA2() ; 
            String aralik2 = " b:" + ex.getB1() +".."+ex.getB2();
            int N = ex.getN();
            Object[] adder = { ex.getIdExercise(), ex.getExerciseName() ,aralik1,aralik2, N};
            exerciseModel.addRow(adder);
        }
        scoresGoruntule();
    }
    
    public void scoresGoruntule(){                          //child nesnesinin exercise bilgilerini goruntuledikten sonra yaptigi skorlari da goruntulemek lazim
        int selectRow = exerciseTable.getSelectedRow();
        scoresModel.setRowCount(0);                 //Tabloyu sifirladik once ondan sonrada artik sirasi ile tabloya eklemem lazim.
        if(selectRow < 0){                                  //Belli basli exercise secili olmali ki tabloya goruntuleyelim.
            return;
        }
        exerciseNameText.setText(exerciseTable.getValueAt(selectRow, 1).toString());
        int exerciseID = Integer.parseInt( exerciseTable.getValueAt(selectRow, 0).toString() );
        exerciseIDtext.setText(exerciseTable.getValueAt(selectRow, 0).toString());
        TreeSet<Exercise> scores = child.getScores().get(exerciseID);
        if(scores == null){                             //child nesnesi daha once alistirma yapmamissa olmayan seyi nasil goruntuleyelim.
            scoresModel.setRowCount(0);
            return;
        }
        for(Exercise ex : scores){
            
            Object[] adder = {ex.getTrueNumber(), ex.getN() - ex.getTrueNumber(), ex.getDuration(), 100*(double)ex.getTrueNumber()/ex.getN()};
            scoresModel.addRow(adder);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        childPanelName = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        exerciseTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        uyari = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scoresTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exerciseIDtext = new javax.swing.JLabel();
        exerciseNameText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Hoşgeldiniz");

        childPanelName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        childPanelName.setText(".");

        exerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "İsim", "Aralık", "Aralık", "Soru Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exerciseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exerciseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(exerciseTable);
        if (exerciseTable.getColumnModel().getColumnCount() > 0) {
            exerciseTable.getColumnModel().getColumn(0).setResizable(false);
            exerciseTable.getColumnModel().getColumn(1).setResizable(false);
            exerciseTable.getColumnModel().getColumn(2).setResizable(false);
            exerciseTable.getColumnModel().getColumn(3).setResizable(false);
            exerciseTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Alıştırmaya Başla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        uyari.setForeground(new java.awt.Color(204, 0, 0));
        uyari.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uyari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uyari)
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alıştırmalarım", jPanel1);

        scoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doğru Sayısı", "Yanlış Sayısı", "Süre(ms)", "Puan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(scoresTable);
        if (scoresTable.getColumnModel().getColumnCount() > 0) {
            scoresTable.getColumnModel().getColumn(0).setResizable(false);
            scoresTable.getColumnModel().getColumn(1).setResizable(false);
            scoresTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Alıştırma İsmi:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("ID:");

        exerciseIDtext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exerciseIDtext.setText(".");

        exerciseNameText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exerciseNameText.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exerciseIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exerciseNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(exerciseIDtext)
                    .addComponent(exerciseNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Alıştırma Skorum", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(childPanelName, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(childPanelName))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exerciseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exerciseTableMouseClicked
        scoresGoruntule();
    }//GEN-LAST:event_exerciseTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Alistirmaya baslama butonu
       //Oncelikle belli bir exercise secmeli ki cozssun.
        int selectRow = exerciseTable.getSelectedRow();
       if(selectRow < 0){
           uyari.setText("Lütfen herhangi bir alıştırma seçiniz...");
           return;
       }
       
        
        int exerciseID = Integer.parseInt( exerciseTable.getValueAt(selectRow, 0).toString() );
        Exercise ex = child.findExercise(exerciseID);
        ex.SoruOlustur();                                    //Neden alistirmaya baslamadan once soru olusturuyorum.
                                                             //Cunku parent nesnesi hep alıstırma tanimladan farkli sorular gorerek egzersiz yapabilsin diye. Her alistirma tusuna bastiginda bir nebze farkli sorular gorecek.
        file.dosyaYazExercise(ex);                           //JExam panel hangi exercise bilgisini goruntuleyecegini bilmesi icin exercise.bin dosyasina yazdim.
        JExam jExam = new JExam(this, true);       //JExam panelini goruntuledik.
        this.setVisible(false);
        jExam.setVisible(true);
        this.dispose();                                     //Artık JChild paneli kapattım. Arkada calismasin
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JChildPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel childPanelName;
    private javax.swing.JLabel exerciseIDtext;
    private javax.swing.JLabel exerciseNameText;
    private javax.swing.JTable exerciseTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable scoresTable;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
