
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Saadettin
 */


public class JParentPanell extends javax.swing.JFrame {
    
    Parent parent;
    FileTransaction file;
    DefaultTableModel childrenTableModel;
    DefaultTableModel exerciseTableModel;
    DefaultTableModel childrenExerciseTableModel;
    DefaultTableModel scoresModel;
    
    public JParentPanell() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            file = new FileTransaction();
            parent = (Parent)file.dosyaInsideOku();
            System.out.println(parent);
            parentNameTextttt.setText(parent.getName());
            childrenTableModel = (DefaultTableModel)ChildrenTable.getModel();
            exerciseTableModel = (DefaultTableModel)ExerciseTable.getModel();
            childrenExerciseTableModel = (DefaultTableModel)childrenExerciseTable.getModel();
            scoresModel = (DefaultTableModel)scoresTable.getModel();
            childGoruntule();
            exerciseGoruntule();
            childExerciseGoruntule();
        } catch (IOException ex) {
            
        }
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                file.dosyaGuncelle(parent);
                file.dosyaSil("inside.bin");
            }
        });
        
    }
    
    public void childGoruntule(){
        childrenTableModel.setRowCount(0);
        ArrayList<Child> children = parent.getChildren();
        
        for(Child child : children){
            Object[] adder = {child.getName(), child.getID(), child.getPassword()};
            childrenTableModel.addRow(adder);
        }
        
    }
    
    public void childExerciseGoruntule(){
        childrenExerciseTableModel.setRowCount(0);
        ArrayList<Child> children = parent.getChildren();
        
        for(Child child : children){
            Object[] adder = {child.getName(), child.getID()};
            childrenExerciseTableModel.addRow(adder);
        }
    }
    
    public void exerciseGoruntule(){
        int selectRow = ChildrenTable.getSelectedRow();
        if(selectRow < 0){
            return;
        }
        exerciseTableModel.setRowCount(0);
        ArrayList<Exercise> exerciseAll = new ArrayList<Exercise>();
        String childID = ChildrenTable.getValueAt(selectRow, 1).toString();
        int id = Integer.parseInt(childID);
        Child child = parent.findChild(id);
        if(child == null){
            return;
        }
        exerciseAll.addAll(child.getExercises());
        
        
        for(Exercise ex : exerciseAll){
            String aralik1 = "a:" + ex.getA1() + ".."+ ex.getA2() ; 
            String aralik2 = " b:" + ex.getB1() +".."+ex.getB2();
            int N = ex.getN();
            Object[] adder = { ex.getIdExercise(), ex.getExerciseName() ,N,aralik1,aralik2};
            exerciseTableModel.addRow(adder);
        }
        scoresGoruntule(child);
    }
    
    public void scoresGoruntule(Child child){
        int selectRow = ExerciseTable.getSelectedRow();
        scoresModel.setRowCount(0);
        if(selectRow < 0){
            return;
        }
        int exerciseID = Integer.parseInt( ExerciseTable.getValueAt(selectRow, 0).toString() );
        TreeSet<Exercise> scores = child.getScores().get(exerciseID);
        if(scores == null){
            return;
        }
        for(Exercise ex : scores){
            Object[] adder = {ex.getTrueNumber(), ex.getN() - ex.getTrueNumber(), ex.getDuration()};
            scoresModel.addRow(adder);
        }
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChildrenTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExerciseTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        childName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        childPassword = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        scoresTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        girAlistirmaİsmi = new javax.swing.JTextField();
        girCarpan1Text = new javax.swing.JTextField();
        girCarpan22Text = new javax.swing.JTextField();
        girCarpan12Text = new javax.swing.JTextField();
        girCarpan2Text = new javax.swing.JTextField();
        girNtext = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        childrenExerciseTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        uyari = new javax.swing.JLabel();
        normalAlistirmaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        parentNameTextttt = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Çocuklarım");

        ChildrenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "İsmi", "ID", "Şifresi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ChildrenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChildrenTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ChildrenTable);
        if (ChildrenTable.getColumnModel().getColumnCount() > 0) {
            ChildrenTable.getColumnModel().getColumn(0).setResizable(false);
            ChildrenTable.getColumnModel().getColumn(1).setResizable(false);
            ChildrenTable.getColumnModel().getColumn(2).setResizable(false);
        }

        ExerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "İsmi", "Soru Sayısı", "Aralık", "Aralık"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ExerciseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExerciseTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ExerciseTable);
        if (ExerciseTable.getColumnModel().getColumnCount() > 0) {
            ExerciseTable.getColumnModel().getColumn(0).setResizable(false);
            ExerciseTable.getColumnModel().getColumn(1).setResizable(false);
            ExerciseTable.getColumnModel().getColumn(3).setResizable(false);
            ExerciseTable.getColumnModel().getColumn(3).setHeaderValue("Aralık");
            ExerciseTable.getColumnModel().getColumn(4).setHeaderValue("Aralık");
        }

        jButton2.setText("Çocuk Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Çocuk İsmi:");

        jLabel12.setText("Şifresi");

        jButton3.setText("Çocuk Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        scoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doğru", "Yanlış", "Süre(ms)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scoresTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoresTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(scoresTable);
        if (scoresTable.getColumnModel().getColumnCount() > 0) {
            scoresTable.getColumnModel().getColumn(0).setResizable(false);
            scoresTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton4.setText("Rapor Elde Et");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Egzersiz Grafiği");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Soru Grafiği");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(childName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(childPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Ana Sayfa", jPanel1);

        jLabel4.setText("Alıştırma İsmi");

        jLabel5.setText("1. çarpanın başlangıç değeri");

        jLabel6.setText("1. çarpanın bitiş değeri");

        jLabel7.setText("2. çarpanın başlangıç değeri");

        jLabel8.setText("2. çarpanın bitiş değeri");

        jLabel9.setText("Kaç tane soru istersiniz");

        childrenExerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "İsmi", "ID"
            }
        ));
        jScrollPane5.setViewportView(childrenExerciseTable);

        jButton1.setText("Alıştırmayı Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        uyari.setForeground(new java.awt.Color(255, 0, 51));
        uyari.setText(".");

        normalAlistirmaButton.setText("Normal Alıştırma Ekle");
        normalAlistirmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalAlistirmaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(uyari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(girCarpan1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(girAlistirmaİsmi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(girCarpan12Text, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(girCarpan2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(girCarpan22Text, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(girNtext, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton1)
                        .addGap(65, 65, 65)
                        .addComponent(normalAlistirmaButton)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(girAlistirmaİsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(girCarpan1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(girCarpan12Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(girCarpan2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(girCarpan22Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(girNtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(uyari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(normalAlistirmaButton))
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Alıştırma Ekle", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Hoşgeldiniz");

        parentNameTextttt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        parentNameTextttt.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parentNameTextttt, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(parentNameTextttt))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    //Couk ekliyoruz.
    String name = childName.getText();
    String password = childPassword.getText();
    if(name.isEmpty() || password.isEmpty()){ //Bos ise herhangi bir islem yapamayiz.
        return;
    }
    //Burada sonID child nesnesinin ID degeri essiz olması icin 1 artirip child ekleyecez. En son hangi child ID bilgisinde kaldigini tutuyordu.
    parent.setSonID();
    Child child = new Child(name, password, parent.getSonID());
    parent.addChild(child);
    childGoruntule();    
    exerciseGoruntule();
    childExerciseGoruntule();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ExerciseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExerciseTableMouseClicked
        int selectRow = ChildrenTable.getSelectedRow();
        if(selectRow < 0){
            return;
        }
        int id = Integer.parseInt( ChildrenTable.getValueAt(selectRow, 1).toString() );
        scoresGoruntule(parent.findChild(id));
    }//GEN-LAST:event_ExerciseTableMouseClicked

    private void ChildrenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChildrenTableMouseClicked
        exerciseGoruntule();
    }//GEN-LAST:event_ChildrenTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //admin tarafindan girilen degerlerle child nesnesine exercise tanimladik
        int selectRow = childrenExerciseTable.getSelectedRow();
        if(selectRow < 0){
            uyari.setText("Lütfen tablodan çocuk seçiiniz...");
            return;
        }
        if(isEmpty()){
            uyari.setText("Boş kutucukları doldurunuz");
            return;
        }
        int N = Integer.parseInt(girNtext.getText() );
        int a1 = Integer.parseInt(girCarpan1Text.getText() );
        int a2 = Integer.parseInt(girCarpan12Text.getText() );
        int b1 = Integer.parseInt(girCarpan2Text.getText() );
        int b2 = Integer.parseInt(girCarpan22Text.getText() );
        if(a2 <= a1 && b2 <= b1){
            JOptionPane.showMessageDialog(null, "İkinci çarpan birinci çarpandan büyük olmalı");
            return;
        }
        String name = girAlistirmaİsmi.getText();
        String childID = childrenExerciseTable.getValueAt(selectRow, 1).toString();
        int id = Integer.parseInt(childID);
        Child child = parent.findChild(id);         //parent nesnesinin icinden belli cocugu secip exercise ekleyecez
        child.addExercise(name, a1, a2, b1, b2, N);
        exerciseGoruntule();
        uyari.setText("Alıştırma eklendi");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectRow = ChildrenTable.getSelectedRow();
        if(selectRow < 0){
            return;
        }
        String childID = ChildrenTable.getValueAt(selectRow, 1).toString();
        int id = Integer.parseInt(childID);
        parent.removeChild(id);         //child nesnesini siliyoruz.
        childGoruntule();                       //guncellendigi icin yeni bilgileri tablolara yansitiyoruz.
        exerciseGoruntule();
        childExerciseGoruntule();
        exerciseTableModel.setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void scoresTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoresTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scoresTableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       //secili child nesnesinin secili exercise nesnesini excel formatina donusturuyor.
        int selectRow = ChildrenTable.getSelectedRow();
       
        if(selectRow < 0 ){
            JOptionPane.showMessageDialog(null, "Tablodan çocuk seçin");
            return;
        }
        int selectRow2 = ExerciseTable.getSelectedRow();
        
        if(selectRow2 < 0 ){
            JOptionPane.showMessageDialog(null, "Tablodan alıştırma seçin");
            return;
        }
        int idChild = Integer.parseInt(childrenExerciseTable.getValueAt(selectRow, 1).toString() );
        int idExercise = Integer.parseInt(ExerciseTable.getValueAt(selectRow2, 0).toString() );
        Child child = parent.findChild(idChild);
        TreeSet<Exercise> exercises = child.getTreeSetExercise(idExercise);
        if(exercises.size() == 0){
             JOptionPane.showMessageDialog(null, "Yapılmış herhangi bir alıştırma yoktur.");
            return;
        }
        file.getExcelFile(child.getName(), exercises);
        JOptionPane.showMessageDialog(null, "İstediğiniz rapor oluşmuştur");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void normalAlistirmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalAlistirmaButtonActionPerformed
        girCarpan1Text.setText("1");
        girCarpan12Text.setText("10");
        girCarpan2Text.setText("1");
        girCarpan22Text.setText("10");
        girNtext.setText("10");
        uyari.setText("Şimdi alıştırma ekle butonuna basabilirsiniz");
    }//GEN-LAST:event_normalAlistirmaButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Burada yapılan alistirmalarda alistirma basina ne kadar yanlis ve dogru soru sayisi yapmis. Onu gisteriyor.
        int selectRow = ChildrenTable.getSelectedRow();
       
        if(selectRow < 0 ){
            JOptionPane.showMessageDialog(null, "Tablodan çocuk seçin");
            return;
        }
        int selectRow2 = ExerciseTable.getSelectedRow();
        
        if(selectRow2 < 0 ){
            JOptionPane.showMessageDialog(null, "Tablodan alıştırma seçin");
            return;
        }
        int idChild = Integer.parseInt(childrenExerciseTable.getValueAt(selectRow, 1).toString() );
        int idExercise = Integer.parseInt(ExerciseTable.getValueAt(selectRow2, 0).toString() );
        String nameExercise = (ExerciseTable.getValueAt(selectRow2, 1).toString() );
        int N = Integer.parseInt(ExerciseTable.getValueAt(selectRow2, 2).toString() );
        Child child = parent.findChild(idChild);
        TreeSet<Exercise> exercises = child.getTreeSetExercise(idExercise);
        if(exercises.isEmpty()){
            JOptionPane.showMessageDialog(null, "Hiç alıştırma yapılmamış.");
            return;
        }
        double totalTrue = 0;
        for(Exercise ex : exercises){                 //exercise nesnelerindeki dogru sayilarini toplayarak toplamda ne kadar dogru sayisi yapmis onu bulduk.
            totalTrue +=ex.getTrueNumber();
        }
        double ratioTrue = 100* (double)totalTrue / (N*exercises.size());        //Alistirma basina dogru sayisi oranini bulduk.
        //Pasta grafigi kullandım. Ondan nesneyi ürettik. Sonra belli basli bilgileri yazdirdik.
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Doğru Soru: "+ratioTrue+"%"+"\nSoru Sayısı: " + N*ratioTrue /100, ratioTrue);
        dataset.setValue("Yanlış Soru: "+(100 - ratioTrue)+"%"+"\nSoru Sayısı: " + (N - N*ratioTrue/100) , 100-ratioTrue);

        // Pasta grafiği oluşturma
        String name = "Alıştırma Başına Doğruluk Oranı\nToplam Yapılan Alıştırma: "+exercises.size();
        JFreeChart chart = ChartFactory.createPieChart(name, dataset, true, true, false);
        // Dilimlere renk ataması yapma
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setSectionPaint("Doğru Soru: "+ratioTrue+"%"+"\nSoru Sayısı: " + N*ratioTrue /100, Color.GREEN);
        plot.setSectionPaint("Yanlış Soru: "+(100 - ratioTrue)+"%"+"\nSoru Sayısı: " + (N - N*ratioTrue/100), Color.RED);
        // Grafiği çerçeveye yerleştirme ve görüntüleme
        ChartFrame frame = new ChartFrame("Ismi: "+ nameExercise +" ID: " + idExercise, chart);
        frame.pack();
        frame.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int selectRow = ChildrenTable.getSelectedRow();
       
        if(selectRow < 0 ){
            JOptionPane.showMessageDialog(null, "Tablodan çocuk seçin");
            return;
        }
        int selectRow2 = ExerciseTable.getSelectedRow();
        
        if(selectRow2 < 0 ){
            JOptionPane.showMessageDialog(null, "Tablodan alıştırma seçin");
            return;
        }
        int idChild = Integer.parseInt(childrenExerciseTable.getValueAt(selectRow, 1).toString() );
        int idExercise = Integer.parseInt(ExerciseTable.getValueAt(selectRow2, 0).toString() );
        String nameExercise = (ExerciseTable.getValueAt(selectRow2, 1).toString() );
        int N = Integer.parseInt(ExerciseTable.getValueAt(selectRow2, 2).toString() );
        Child child = parent.findChild(idChild);
        TreeSet<Exercise> exercises = child.getTreeSetExercise(idExercise);
        if(exercises.isEmpty()){
            JOptionPane.showMessageDialog(null, "Hiç alıştırma yapılmamış.");
            return;
        }
        
        

        // Veri setini oluştur
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int i = 0;
        for(Exercise ex : exercises){
            dataset.addValue(ex.getTrueNumber(), "Doğru", ex.getIdExercise() +"." + i);
            dataset.addValue(N-ex.getTrueNumber(), "Yanlış", ex.getIdExercise() +"." + i);
            i++;
        }

        // Sütun grafiğini oluştur
        //Burada artik yapilan her sorunun dogru ve yanlis sayilarini gorebilecek admin
        JFreeChart chart = ChartFactory.createBarChart(
                "Doğru-Yanlış Sayıları\nToplam Soru: " + N, // Grafik başlığı
                nameExercise+" Adlı Alıştırma ID: " + idExercise, // X ekseni etiketi
                "Soru Sayısı", // Y ekseni etiketi
                dataset // Veri seti
        );

        // Y ekseni aralığını ayarla
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setTickUnit(new NumberTickUnit(1)); // Y ekseni işaretli değerlerini 1 birim aralıklarla ayarla
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, Color.GREEN); // Doğru sütunları yeşil renkte ayarla
        renderer.setSeriesPaint(1, Color.RED); // Yanlış sütunları kırmızı renkte ayarla
        
        ChartFrame frame = new ChartFrame("Yapılan Alıştırmalar", chart);
        frame.pack();
        frame.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    public boolean isEmpty(){                   //JText degerleri dolu mu bos mu onun kontrolu
        return girNtext.getText().isEmpty()||
                girCarpan1Text.getText().isEmpty() ||
                girCarpan12Text.getText().isEmpty() ||
                girCarpan2Text.getText().isEmpty() ||
                girCarpan22Text.getText().isEmpty() ||
                girAlistirmaİsmi.getText().isEmpty();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JParentPanell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JParentPanell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JParentPanell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JParentPanell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JParentPanell().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ChildrenTable;
    private javax.swing.JTable ExerciseTable;
    private javax.swing.JTextField childName;
    private javax.swing.JTextField childPassword;
    private javax.swing.JTable childrenExerciseTable;
    private javax.swing.JTextField girAlistirmaİsmi;
    private javax.swing.JTextField girCarpan12Text;
    private javax.swing.JTextField girCarpan1Text;
    private javax.swing.JTextField girCarpan22Text;
    private javax.swing.JTextField girCarpan2Text;
    private javax.swing.JTextField girNtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton normalAlistirmaButton;
    private javax.swing.JLabel parentNameTextttt;
    private javax.swing.JTable scoresTable;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
